# Generated by Django 6.0.6 on 2026-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_currencyconfig_payment_extended'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Exchange rate applied at payment time (USD to selected currency)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(blank=True, help_text='Mobile money provider (M-Pesa, Airtel...) or card network', max_length=50),
        ),
    ]
