# Generated by Django 6.0.7 on 2026-07-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled (no refund)')], default='pending', max_length=20),
        ),
    ]
