# Generated by Django 6.0.7 on 2026-07-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_grandfather_existing_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('traveller', 'Traveller'), ('owner', 'Property Owner'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('support', 'Support'), ('finance', 'Finance')], default='traveller', max_length=30),
        ),
    ]
