# Generated by Django 6.0.7 on 2026-07-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_accessibility_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(blank=True, help_text='Area within the city, e.g. Kigamboni, Tabata, Masaki, Mikocheni.', max_length=100),
        ),
    ]
