# Generated by Django 6.0.6 on 2026-06-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('concentration', models.CharField(choices=[('edc', 'Eau de Cologne (EDC)'), ('edt', 'Eau de Toilette (EDT)'), ('edp', 'Eau de Parfum (EDP)'), ('parfum', 'Parfum / Extrait')], default='edp', max_length=10)),
                ('bottle_size', models.CharField(choices=[('10ml', '10 ml'), ('30ml', '30 ml'), ('50ml', '50 ml'), ('75ml', '75 ml'), ('100ml', '100 ml'), ('200ml', '200 ml')], default='50ml', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price (TZS)', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost / purchase price', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10, help_text='Alert when stock drops to this level')),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fragrances/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
    ]
