"""
Django settings for bookmystay project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7mvlka7bl-_hi8fxs1y_*38b1+ne+%^+r-ai84qz^w#g)-rm6s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'properties',
    'payments',
    'reviews',
    'bookings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookmystay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmystay.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

JAZZMIN_SETTINGS = {
    # ─── BRANDING ───────────────────────────────────────
    "site_title":        "BookMyStay Admin",
    "site_header":       "BookMyStay",
    "site_brand":        "BookMyStay",
    "welcome_sign":      "Welcome to BookMyStay Admin Panel",
    "copyright":         "BookMyStay Tanzania © 2025",

    # ─── ICONS ──────────────────────────────────────────
    "site_icon": None,
    "site_logo": None,

    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
        {"name": "View Site", "url": "/", "new_window": True},
        {"name": "Properties", "url": "/properties/", "new_window": True},
    ],

    # ─── USER MENU ──────────────────────────────────────
    "usermenu_links": [
        {"name": "View Site", "url": "/", "new_window": True},
    ],

    # ─── SIDEBAR ────────────────────────────────────────
    "show_sidebar":          True,
    "navigation_expanded":   True,
    "hide_apps":             [],
    "hide_models":           [],

    "order_with_respect_to": [
        "users",
        "properties",
        "bookings",
        "payments",
        "reviews",
    ],

    # ─── MODEL ICONS ────────────────────────────────────
    "icons": {
        "auth":                     "fas fa-users-cog",
        "users.user":               "fas fa-user",
        "properties.property":      "fas fa-building",
        "properties.propertyimage": "fas fa-image",
        "properties.propertyextra": "fas fa-concierge-bell",
        "properties.amenity":       "fas fa-wifi",
        "properties.propertyamenity": "fas fa-check-circle",
        "bookings.cart":            "fas fa-shopping-cart",
        "bookings.cartitem":        "fas fa-plus-circle",
        "bookings.booking":         "fas fa-calendar-check",
        "bookings.bookingextra":    "fas fa-receipt",
        "payments.payment":         "fas fa-credit-card",
        "reviews.review":           "fas fa-star",
    },

    "default_icon_parents":  "fas fa-folder",
    "default_icon_children": "fas fa-circle",

    # ─── RELATED MODAL ──────────────────────────────────
    "related_modal_active": True,

    # ─── UI TWEAKS ──────────────────────────────────────
    "custom_css": None,
    "custom_js":  None,
    "use_google_fonts_cdn": True,
    "show_ui_builder":      False,
    "changeform_format":    "horizontal_tabs",

    "changeform_format_overrides": {
        "auth.user":  "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text":      False,
    "footer_small_text":      False,
    "body_small_text":        False,
    "brand_small_text":       False,
    "brand_colour":           "navbar-dark",
    "accent":                 "accent-orange",
    "navbar":                 "navbar-dark",
    "no_navbar_border":       True,
    "navbar_fixed":           True,
    "layout_boxed":           False,
    "footer_fixed":           False,
    "sidebar_fixed":          True,
    "sidebar":                "sidebar-dark-orange",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style":  False,
    "sidebar_nav_flat_style":    False,
    "theme":                  "flatly",
    "dark_mode_theme":        "darkly",
    "button_classes": {
        "primary":   "btn-primary",
        "secondary": "btn-secondary",
        "info":      "btn-info",
        "warning":   "btn-warning",
        "danger":    "btn-danger",
        "success":   "btn-success",
    },
}