# Generated by Django 6.0.7 on 2026-07-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_adults_booking_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
    ]
