# Generated by Django 6.0.7 on 2026-07-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_cart_children_cart_special_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cancellation_policy',
            field=models.CharField(blank=True, choices=[('flexible', 'Flexible — full refund up to 24h before check-in'), ('moderate', 'Moderate — full refund up to 5 days before check-in'), ('strict', 'Strict — 50% refund up to 7 days before check-in')], max_length=20),
        ),
    ]
