# Generated by Django 6.0.7 on 2026-07-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_cancellation_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='goodbye_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
